import { db } from './index';
import { restaurants, users, userPreferences, availabilitySlots, bookings, reviews } from './schema';
import { hash } from 'bcryptjs';
import { addDays, addHours, setHours, setMinutes } from 'date-fns';

const NYC_RESTAURANTS = [
  {
    name: "Le Bernardin",
    description: "Elegant French seafood restaurant with impeccable service and exquisite dishes",
    cuisine: "French",
    priceRange: 4,
    neighborhood: "Midtown West",
    address: "155 W 51st St, New York, NY 10019",
    phone: "(212) 554-1515",
    website: "https://le-bernardin.com",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    rating: 4.8,
    reviewCount: 2450,
    features: ["Fine Dining", "Michelin Star", "Romantic", "Wine Bar"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Carbone",
    description: "Iconic Italian-American restaurant serving classic red sauce dishes in a retro setting",
    cuisine: "Italian",
    priceRange: 4,
    neighborhood: "Greenwich Village",
    address: "181 Thompson St, New York, NY 10012",
    phone: "(212) 254-3000",
    website: "https://carbonenewyork.com",
    imageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
    rating: 4.7,
    reviewCount: 3200,
    features: ["Italian-American", "Classic", "Date Night", "Celebrity Spot"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Peter Luger Steak House",
    description: "Historic steakhouse known for dry-aged porterhouse and old-school atmosphere",
    cuisine: "Steakhouse",
    priceRange: 4,
    neighborhood: "Williamsburg",
    address: "178 Broadway, Brooklyn, NY 11211",
    phone: "(718) 387-7400",
    website: "https://peterluger.com",
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462",
    rating: 4.6,
    reviewCount: 5600,
    features: ["Cash Only", "Historic", "Dry-Aged Beef", "No Reservations Online"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Momofuku Noodle Bar",
    description: "Trendy spot for innovative ramen, pork buns, and Asian-fusion dishes",
    cuisine: "Asian Fusion",
    priceRange: 2,
    neighborhood: "East Village",
    address: "171 1st Ave, New York, NY 10003",
    phone: "(212) 777-7773",
    website: "https://momofuku.com",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    rating: 4.4,
    reviewCount: 4100,
    features: ["Ramen", "Casual", "Innovative", "Counter Seating"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Gramercy Tavern",
    description: "Elegant American restaurant with seasonal menu and warm, rustic decor",
    cuisine: "American",
    priceRange: 4,
    neighborhood: "Gramercy",
    address: "42 E 20th St, New York, NY 10003",
    phone: "(212) 477-0777",
    website: "https://gramercytavern.com",
    imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
    rating: 4.7,
    reviewCount: 3800,
    features: ["Seasonal Menu", "Farm-to-Table", "Wine List", "Michelin Star"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Eleven Madison Park",
    description: "Three Michelin star restaurant offering a plant-based tasting menu experience",
    cuisine: "Contemporary",
    priceRange: 4,
    neighborhood: "Flatiron",
    address: "11 Madison Ave, New York, NY 10010",
    phone: "(212) 889-0905",
    website: "https://elevenmadisonpark.com",
    imageUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c",
    rating: 4.9,
    reviewCount: 2100,
    features: ["Three Michelin Stars", "Plant-Based", "Tasting Menu", "Special Occasion"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Katz's Delicatessen",
    description: "Historic Jewish deli famous for pastrami sandwiches and old New York charm",
    cuisine: "Deli",
    priceRange: 2,
    neighborhood: "Lower East Side",
    address: "205 E Houston St, New York, NY 10002",
    phone: "(212) 254-2246",
    website: "https://katzsdelicatessen.com",
    imageUrl: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af",
    rating: 4.5,
    reviewCount: 8900,
    features: ["Historic", "Pastrami", "Casual", "Tourist Favorite"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Sushi Nakazawa",
    description: "Omakase sushi restaurant featuring Chef Nakazawa's meticulous technique",
    cuisine: "Japanese",
    priceRange: 4,
    neighborhood: "West Village",
    address: "23 Commerce St, New York, NY 10014",
    phone: "(212) 924-2212",
    website: "https://sushinakazawa.com",
    imageUrl: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351",
    rating: 4.8,
    reviewCount: 1850,
    features: ["Omakase", "Sushi Bar", "Michelin Star", "Intimate"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Mission Chinese Food",
    description: "Bold Chinese-American cuisine with a punk rock attitude and spicy flavors",
    cuisine: "Chinese",
    priceRange: 2,
    neighborhood: "Lower East Side",
    address: "171 E Broadway, New York, NY 10002",
    phone: "(212) 432-0300",
    website: "https://missionchinesefood.com",
    imageUrl: "https://images.unsplash.com/photo-1526318896980-cf78c088247c",
    rating: 4.3,
    reviewCount: 2700,
    features: ["Spicy", "Innovative", "Casual", "Trendy"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "The Spotted Pig",
    description: "British-inspired gastropub with elevated comfort food and craft beers",
    cuisine: "British",
    priceRange: 3,
    neighborhood: "West Village",
    address: "314 W 11th St, New York, NY 10014",
    phone: "(212) 620-0393",
    website: "https://thespottedpig.com",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1",
    rating: 4.4,
    reviewCount: 4200,
    features: ["Gastropub", "Burger", "Michelin Star", "Late Night"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Cosme",
    description: "Modern Mexican restaurant from Chef Enrique Olvera with creative dishes",
    cuisine: "Mexican",
    priceRange: 3,
    neighborhood: "Flatiron",
    address: "35 E 21st St, New York, NY 10010",
    phone: "(212) 913-9659",
    website: "https://cosmenyc.com",
    imageUrl: "https://images.unsplash.com/photo-1565299507177-b0ac66763828",
    rating: 4.6,
    reviewCount: 3100,
    features: ["Modern Mexican", "Cocktails", "Stylish", "Duck Carnitas"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Marea",
    description: "Upscale Italian seafood restaurant with handmade pasta and oyster bar",
    cuisine: "Italian",
    priceRange: 4,
    neighborhood: "Central Park South",
    address: "240 Central Park S, New York, NY 10019",
    phone: "(212) 582-5100",
    website: "https://marea-nyc.com",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    rating: 4.7,
    reviewCount: 2600,
    features: ["Seafood", "Pasta", "Two Michelin Stars", "Oyster Bar"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Balthazar",
    description: "Bustling French brasserie serving classic bistro fare in a lively atmosphere",
    cuisine: "French",
    priceRange: 3,
    neighborhood: "SoHo",
    address: "80 Spring St, New York, NY 10012",
    phone: "(212) 965-1414",
    website: "https://balthazarny.com",
    imageUrl: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17",
    rating: 4.5,
    reviewCount: 6700,
    features: ["Brasserie", "Bakery", "Brunch", "Classic"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Shake Shack",
    description: "Popular burger chain known for ShackBurgers, crinkle-cut fries, and shakes",
    cuisine: "American",
    priceRange: 1,
    neighborhood: "Multiple Locations",
    address: "Madison Square Park, New York, NY 10010",
    phone: "(212) 889-6600",
    website: "https://shakeshack.com",
    imageUrl: "https://images.unsplash.com/photo-1551782450-17144efb9c50",
    rating: 4.3,
    reviewCount: 12000,
    features: ["Fast Casual", "Burgers", "Outdoor Seating", "Family Friendly"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Ippudo",
    description: "Japanese ramen chain serving rich tonkotsu broth and perfectly cooked noodles",
    cuisine: "Japanese",
    priceRange: 2,
    neighborhood: "East Village",
    address: "65 4th Ave, New York, NY 10003",
    phone: "(212) 388-0088",
    website: "https://ippudony.com",
    imageUrl: "https://images.unsplash.com/photo-1591814468924-caf88d1232e1",
    rating: 4.4,
    reviewCount: 5200,
    features: ["Ramen", "Japanese", "Casual", "Quick Bites"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Blue Hill",
    description: "Farm-to-table pioneer serving seasonal American cuisine in a former speakeasy",
    cuisine: "American",
    priceRange: 4,
    neighborhood: "Greenwich Village",
    address: "75 Washington Pl, New York, NY 10011",
    phone: "(212) 539-1776",
    website: "https://bluehillfarm.com",
    imageUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de",
    rating: 4.6,
    reviewCount: 1900,
    features: ["Farm-to-Table", "Sustainable", "Michelin Star", "Romantic"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Roberta's",
    description: "Hip Bushwick pizzeria known for wood-fired pies and creative toppings",
    cuisine: "Pizza",
    priceRange: 2,
    neighborhood: "Bushwick",
    address: "261 Moore St, Brooklyn, NY 11206",
    phone: "(718) 417-1118",
    website: "https://robertaspizza.com",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
    rating: 4.5,
    reviewCount: 7800,
    features: ["Pizza", "Hip", "Garden", "Brooklyn"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Per Se",
    description: "Thomas Keller's luxurious tasting menu restaurant with Central Park views",
    cuisine: "Contemporary",
    priceRange: 4,
    neighborhood: "Columbus Circle",
    address: "10 Columbus Circle, New York, NY 10019",
    phone: "(212) 823-9335",
    website: "https://thomaskeller.com/perseny",
    imageUrl: "https://images.unsplash.com/photo-1592861956120-e524fc739696",
    rating: 4.8,
    reviewCount: 1600,
    features: ["Three Michelin Stars", "Tasting Menu", "Central Park Views", "Thomas Keller"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "RedFarm",
    description: "Inventive Chinese dim sum and creative cocktails in a stylish space",
    cuisine: "Chinese",
    priceRange: 3,
    neighborhood: "West Village",
    address: "529 Hudson St, New York, NY 10014",
    phone: "(212) 792-9700",
    website: "https://redfarmnyc.com",
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb",
    rating: 4.5,
    reviewCount: 4500,
    features: ["Dim Sum", "Creative", "Small Plates", "Fun"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "L'Artusi",
    description: "Contemporary Italian with exceptional pasta and an extensive wine list",
    cuisine: "Italian",
    priceRange: 3,
    neighborhood: "West Village",
    address: "228 W 10th St, New York, NY 10014",
    phone: "(212) 255-5757",
    website: "https://lartusi.com",
    imageUrl: "https://images.unsplash.com/photo-1595295333158-4742f28fbd85",
    rating: 4.6,
    reviewCount: 3400,
    features: ["Pasta", "Wine Bar", "Date Night", "Modern Italian"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Minetta Tavern",
    description: "Historic Greenwich Village tavern famous for the Black Label Burger",
    cuisine: "French",
    priceRange: 3,
    neighborhood: "Greenwich Village",
    address: "113 MacDougal St, New York, NY 10012",
    phone: "(212) 475-3850",
    website: "https://minettatavern.com",
    imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    rating: 4.5,
    reviewCount: 5100,
    features: ["Historic", "Black Label Burger", "French Bistro", "Celebrities"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Olmsted",
    description: "Inventive New American cuisine with ingredients from their backyard garden",
    cuisine: "American",
    priceRange: 3,
    neighborhood: "Prospect Heights",
    address: "659 Vanderbilt Ave, Brooklyn, NY 11238",
    phone: "(718) 552-2610",
    website: "https://olmstednyc.com",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    rating: 4.7,
    reviewCount: 2200,
    features: ["Garden", "Innovative", "Michelin Star", "Brooklyn"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Don Angie",
    description: "Italian-American spot serving shareable pasta dishes and creative cocktails",
    cuisine: "Italian",
    priceRange: 3,
    neighborhood: "West Village",
    address: "103 Greenwich Ave, New York, NY 10014",
    phone: "(212) 889-8884",
    website: "https://donangie.com",
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
    rating: 4.6,
    reviewCount: 2900,
    features: ["Pasta", "Shareable", "Fun", "Trendy"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Oxalis",
    description: "Neo-bistro with market-driven French cuisine and natural wines",
    cuisine: "French",
    priceRange: 3,
    neighborhood: "Prospect Heights",
    address: "791 Washington Ave, Brooklyn, NY 11238",
    phone: "(929) 314-8670",
    website: "https://oxalisbrooklyn.com",
    imageUrl: "https://images.unsplash.com/photo-1481931098730-318b6f776db0",
    rating: 4.7,
    reviewCount: 1400,
    features: ["Neo-Bistro", "Natural Wine", "Seasonal", "Intimate"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Xi'an Famous Foods",
    description: "Fast-casual chain specializing in spicy hand-pulled noodles and lamb dishes",
    cuisine: "Chinese",
    priceRange: 1,
    neighborhood: "Multiple Locations",
    address: "24 W 45th St, New York, NY 10036",
    phone: "(212) 786-2068",
    website: "https://xianfoods.com",
    imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43",
    rating: 4.4,
    reviewCount: 6300,
    features: ["Hand-Pulled Noodles", "Spicy", "Quick", "Casual"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Daniel",
    description: "Daniel Boulud's flagship offering refined French haute cuisine",
    cuisine: "French",
    priceRange: 4,
    neighborhood: "Upper East Side",
    address: "60 E 65th St, New York, NY 10065",
    phone: "(212) 288-0033",
    website: "https://danielnyc.com",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    rating: 4.8,
    reviewCount: 2800,
    features: ["Two Michelin Stars", "French Haute Cuisine", "Elegant", "Daniel Boulud"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Lilia",
    description: "Brooklyn Italian serving exceptional pasta and wood-fired seafood",
    cuisine: "Italian",
    priceRange: 3,
    neighborhood: "Williamsburg",
    address: "567 Union Ave, Brooklyn, NY 11222",
    phone: "(718) 576-3095",
    website: "https://lilianewyork.com",
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601",
    rating: 4.7,
    reviewCount: 4100,
    features: ["Pasta", "Wood-Fired", "Brooklyn", "Hard to Book"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Atomix",
    description: "Korean fine dining with innovative tasting menu and sleek design",
    cuisine: "Korean",
    priceRange: 4,
    neighborhood: "NoMad",
    address: "104 E 30th St, New York, NY 10016",
    phone: "(646) 876-8086",
    website: "https://atomixnyc.com",
    imageUrl: "https://images.unsplash.com/photo-1582547564925-947f7c4aab10",
    rating: 4.9,
    reviewCount: 950,
    features: ["Tasting Menu", "Two Michelin Stars", "Korean", "Modern"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Via Carota",
    description: "Charming West Village Italian serving rustic dishes and natural wines",
    cuisine: "Italian",
    priceRange: 3,
    neighborhood: "West Village",
    address: "51 Grove St, New York, NY 10014",
    phone: "(212) 255-1962",
    website: "https://viacarota.com",
    imageUrl: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590",
    rating: 4.6,
    reviewCount: 5200,
    features: ["Rustic Italian", "No Reservations", "Natural Wine", "Cozy"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Crown Shy",
    description: "Modern American fine dining in the Financial District with inventive dishes",
    cuisine: "American",
    priceRange: 3,
    neighborhood: "Financial District",
    address: "70 Pine St, New York, NY 10005",
    phone: "(212) 517-1932",
    website: "https://crownshy.nyc",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947",
    rating: 4.7,
    reviewCount: 1800,
    features: ["Modern American", "Michelin Star", "Business Lunch", "Elegant"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Rangoon",
    description: "Burmese restaurant bringing bold flavors and tea leaf salad to Brooklyn",
    cuisine: "Burmese",
    priceRange: 2,
    neighborhood: "Fort Greene",
    address: "62 DeKalb Ave, Brooklyn, NY 11201",
    phone: "(347) 799-2165",
    website: "https://rangoonnyc.com",
    imageUrl: "https://images.unsplash.com/photo-1529042410759-befb1204b468",
    rating: 4.5,
    reviewCount: 1650,
    features: ["Burmese", "Tea Leaf Salad", "Brooklyn", "Unique"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Lucali",
    description: "Cash-only Carroll Gardens pizzeria with a cult following",
    cuisine: "Pizza",
    priceRange: 2,
    neighborhood: "Carroll Gardens",
    address: "575 Henry St, Brooklyn, NY 11231",
    phone: "(718) 858-4086",
    website: "https://lucali.com",
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38",
    rating: 4.7,
    reviewCount: 4800,
    features: ["Pizza", "Cash Only", "No Reservations", "BYOB"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Claro",
    description: "Oaxacan restaurant highlighting regional Mexican cuisine and mezcal",
    cuisine: "Mexican",
    priceRange: 3,
    neighborhood: "Gowanus",
    address: "284 3rd Ave, Brooklyn, NY 11215",
    phone: "(347) 721-3126",
    website: "https://clarobrooklyn.com",
    imageUrl: "https://images.unsplash.com/photo-1599974789516-605432dd6f40",
    rating: 4.6,
    reviewCount: 1950,
    features: ["Oaxacan", "Mezcal", "Regional Mexican", "Garden"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Frankies 457 Spuntino",
    description: "Neighborhood Italian spot known for meatballs and backyard garden",
    cuisine: "Italian",
    priceRange: 2,
    neighborhood: "Carroll Gardens",
    address: "457 Court St, Brooklyn, NY 11231",
    phone: "(718) 403-0033",
    website: "https://frankiespuntino.com",
    imageUrl: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8",
    rating: 4.4,
    reviewCount: 3900,
    features: ["Italian", "Meatballs", "Garden", "Neighborhood Gem"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Hangawi",
    description: "Tranquil Korean vegan restaurant with temple cuisine and floor seating",
    cuisine: "Korean",
    priceRange: 3,
    neighborhood: "Koreatown",
    address: "12 E 32nd St, New York, NY 10016",
    phone: "(212) 213-0077",
    website: "https://hangawirestaurant.com",
    imageUrl: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9",
    rating: 4.5,
    reviewCount: 2400,
    features: ["Vegan", "Korean Temple Cuisine", "No Shoes", "Peaceful"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Kochi",
    description: "Korean fine dining with a seasonal tasting menu and creative execution",
    cuisine: "Korean",
    priceRange: 4,
    neighborhood: "Hell's Kitchen",
    address: "652 10th Ave, New York, NY 10036",
    phone: "(646) 678-4065",
    website: "https://kochirestaurant.com",
    imageUrl: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b",
    rating: 4.8,
    reviewCount: 780,
    features: ["Tasting Menu", "Michelin Star", "Korean", "Intimate"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Emmy Squared",
    description: "Detroit-style pizza with crispy edges and creative toppings",
    cuisine: "Pizza",
    priceRange: 2,
    neighborhood: "Multiple Locations",
    address: "364 Grand St, Brooklyn, NY 11211",
    phone: "(718) 360-4535",
    website: "https://emmysquared.com",
    imageUrl: "https://images.unsplash.com/photo-1571407970349-bc81e7e96c47",
    rating: 4.5,
    reviewCount: 3700,
    features: ["Detroit-Style Pizza", "Casual", "Craft Beer", "Wings"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Superiority Burger",
    description: "Tiny vegetarian burger joint with cult status and creative sandwiches",
    cuisine: "Vegetarian",
    priceRange: 1,
    neighborhood: "East Village",
    address: "119 Avenue A, New York, NY 10009",
    phone: "(212) 256-1192",
    website: "https://superiorityburger.com",
    imageUrl: "https://images.unsplash.com/photo-1520072959219-c595dc870360",
    rating: 4.6,
    reviewCount: 2100,
    features: ["Vegetarian", "Burgers", "Tiny", "Cult Following"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Kesté Pizza & Vino",
    description: "Authentic Neapolitan pizza certified by the True Neapolitan Pizza Association",
    cuisine: "Pizza",
    priceRange: 2,
    neighborhood: "West Village",
    address: "271 Bleecker St, New York, NY 10014",
    phone: "(212) 243-1500",
    website: "https://kestepizzeria.com",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002",
    rating: 4.4,
    reviewCount: 4600,
    features: ["Neapolitan Pizza", "Certified", "Wine", "Casual"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Atoboy",
    description: "Korean small plates with refined technique and beautiful presentation",
    cuisine: "Korean",
    priceRange: 3,
    neighborhood: "NoMad",
    address: "43 E 28th St, New York, NY 10016",
    phone: "(646) 476-7217",
    website: "https://atoboynyc.com",
    imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733",
    rating: 4.6,
    reviewCount: 1900,
    features: ["Small Plates", "Korean", "Michelin Star", "Refined"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Laser Wolf",
    description: "Israeli grill house on a Williamsburg rooftop with shipudim and views",
    cuisine: "Israeli",
    priceRange: 3,
    neighborhood: "Williamsburg",
    address: "97 S 9th St, Brooklyn, NY 11211",
    phone: "(718) 963-3500",
    website: "https://laserwolfbk.com",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947",
    rating: 4.6,
    reviewCount: 2300,
    features: ["Israeli", "Rooftop", "Shipudim", "Views"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Hometown Bar-B-Que",
    description: "Texas-style BBQ in Red Hook with smoky brisket and live music",
    cuisine: "BBQ",
    priceRange: 2,
    neighborhood: "Red Hook",
    address: "454 Van Brunt St, Brooklyn, NY 11231",
    phone: "(347) 294-4644",
    website: "https://hometownbbq.com",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1",
    rating: 4.5,
    reviewCount: 5100,
    features: ["BBQ", "Brisket", "Live Music", "Outdoor Seating"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Oiji Mi",
    description: "Modern Korean cuisine with a Korean-American perspective and creative dishes",
    cuisine: "Korean",
    priceRange: 3,
    neighborhood: "Flatiron",
    address: "17 W 19th St, New York, NY 10011",
    phone: "(646) 767-9050",
    website: "https://oijimi.com",
    imageUrl: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54",
    rating: 4.7,
    reviewCount: 1450,
    features: ["Korean-American", "Michelin Star", "Creative", "Date Night"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Llama Inn",
    description: "Peruvian restaurant with a rooftop overlooking the Brooklyn skyline",
    cuisine: "Peruvian",
    priceRange: 3,
    neighborhood: "Williamsburg",
    address: "50 Withers St, Brooklyn, NY 11211",
    phone: "(718) 387-3434",
    website: "https://llamainnnyc.com",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1",
    rating: 4.5,
    reviewCount: 2700,
    features: ["Peruvian", "Rooftop", "Ceviche", "Pisco Sours"],
    resyEnabled: true,
    opentableEnabled: true,
  },
  {
    name: "Tatiana",
    description: "Modern Russian-Jewish cuisine by Kwame Onwuachi with vibrant atmosphere",
    cuisine: "Russian",
    priceRange: 4,
    neighborhood: "Lincoln Center",
    address: "10 Lincoln Center Plaza, New York, NY 10023",
    phone: "(212) 671-2800",
    website: "https://tatianalincolncenter.com",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    rating: 4.7,
    reviewCount: 1200,
    features: ["Russian-Jewish", "Lincoln Center", "Kwame Onwuachi", "Vibrant"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Madame Vo",
    description: "Vietnamese restaurant specializing in banh mi and traditional dishes",
    cuisine: "Vietnamese",
    priceRange: 2,
    neighborhood: "East Village",
    address: "212 E 10th St, New York, NY 10003",
    phone: "(212) 228-2655",
    website: "https://madamevo.com",
    imageUrl: "https://images.unsplash.com/photo-1559314809-0d155014e29e",
    rating: 4.5,
    reviewCount: 3100,
    features: ["Vietnamese", "Banh Mi", "Casual", "Authentic"],
    resyEnabled: false,
    opentableEnabled: true,
  },
  {
    name: "Russ & Daughters Cafe",
    description: "Historic appetizing shop serving bagels, lox, and Jewish specialties",
    cuisine: "Jewish",
    priceRange: 2,
    neighborhood: "Lower East Side",
    address: "127 Orchard St, New York, NY 10002",
    phone: "(212) 475-4881",
    website: "https://russanddaughters.com",
    imageUrl: "https://images.unsplash.com/photo-1495147466023-ac5c588e2e94",
    rating: 4.6,
    reviewCount: 4900,
    features: ["Bagels", "Lox", "Historic", "Brunch"],
    resyEnabled: false,
    opentableEnabled: false,
  },
  {
    name: "Atera",
    description: "Nordic-inspired tasting menu in an intimate chef's counter setting",
    cuisine: "Nordic",
    priceRange: 4,
    neighborhood: "TriBeCa",
    address: "77 Worth St, New York, NY 10013",
    phone: "(212) 226-1444",
    website: "https://ateranyc.com",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    rating: 4.8,
    reviewCount: 890,
    features: ["Tasting Menu", "Two Michelin Stars", "Chef's Counter", "Nordic"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "COTE",
    description: "Modern Korean steakhouse with premium cuts and tableside grilling",
    cuisine: "Korean",
    priceRange: 4,
    neighborhood: "Flatiron",
    address: "16 W 22nd St, New York, NY 10010",
    phone: "(212) 401-7986",
    website: "https://cotenyc.com",
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462",
    rating: 4.7,
    reviewCount: 3600,
    features: ["Korean BBQ", "Steakhouse", "Michelin Star", "Butcher's Feast"],
    resyEnabled: true,
    opentableEnabled: false,
  },
  {
    name: "Joe's Pizza",
    description: "Classic New York slice joint serving simple, delicious pizza since 1975",
    cuisine: "Pizza",
    priceRange: 1,
    neighborhood: "Greenwich Village",
    address: "7 Carmine St, New York, NY 10014",
    phone: "(212) 366-1182",
    website: "https://joespizzanyc.com",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
    rating: 4.4,
    reviewCount: 8700,
    features: ["NY Slice", "Classic", "Quick", "Late Night"],
    resyEnabled: false,
    opentableEnabled: false,
  },
];

async function seedRestaurants() {
  console.log('Seeding restaurants...');

  for (const restaurant of NYC_RESTAURANTS) {
    const [insertedRestaurant] = await db.insert(restaurants).values(restaurant).returning();
    console.log(`Added: ${insertedRestaurant.name}`);

    // Generate availability for the next 7 days
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    for (let dayOffset = 0; dayOffset < 7; dayOffset++) {
      const date = addDays(today, dayOffset);

      // Generate time slots (5:00 PM to 10:00 PM, every 30 minutes)
      const times = ['17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00'];
      const partySizes = [2, 4, 6];

      for (const time of times) {
        for (const partySize of partySizes) {
          // Randomly make some slots unavailable (70% available)
          const available = Math.random() > 0.3;

          // Determine platform
          let platform = 'direct';
          if (restaurant.resyEnabled && !restaurant.opentableEnabled) platform = 'resy';
          else if (!restaurant.resyEnabled && restaurant.opentableEnabled) platform = 'opentable';
          else if (restaurant.resyEnabled && restaurant.opentableEnabled) {
            platform = Math.random() > 0.5 ? 'resy' : 'opentable';
          }

          await db.insert(availabilitySlots).values({
            restaurantId: insertedRestaurant.id,
            date,
            time,
            partySize,
            available,
            platform,
          });
        }
      }
    }
  }

  console.log(`✓ Seeded ${NYC_RESTAURANTS.length} restaurants with availability`);
}

async function seedTestUser() {
  console.log('Seeding test user...');

  const hashedPassword = await hash('password123', 10);

  const [user] = await db.insert(users).values({
    email: 'test@example.com',
    name: 'Test User',
    password: hashedPassword,
    emailVerified: new Date(),
  }).returning();

  await db.insert(userPreferences).values({
    userId: user.id,
    cuisinePreferences: ['Italian', 'Japanese', 'French'],
    priceRangeMin: 2,
    priceRangeMax: 4,
    dietaryRestrictions: [],
    preferredNeighborhoods: ['West Village', 'Greenwich Village', 'SoHo'],
  });

  console.log(`✓ Created test user: ${user.email} / password123`);

  return user;
}

async function seedTestBookingsAndReviews(userId: string) {
  console.log('Seeding test bookings and reviews...');

  // Get some restaurants
  const allRestaurants = await db.select().from(restaurants).limit(10);

  // Create a past booking with review
  const pastDate = addDays(new Date(), -7);
  const [pastBooking] = await db.insert(bookings).values({
    userId,
    restaurantId: allRestaurants[0].id,
    date: pastDate,
    time: '19:00',
    partySize: 2,
    status: 'confirmed',
    platform: 'resy',
    externalBookingId: 'RESY-' + Math.random().toString(36).substr(2, 9).toUpperCase(),
  }).returning();

  await db.insert(reviews).values({
    userId,
    restaurantId: allRestaurants[0].id,
    bookingId: pastBooking.id,
    rating: 5,
    review: 'Amazing food and service! The pasta was incredible.',
  });

  // Create an upcoming booking
  const futureDate = addDays(new Date(), 3);
  await db.insert(bookings).values({
    userId,
    restaurantId: allRestaurants[1].id,
    date: futureDate,
    time: '20:00',
    partySize: 4,
    status: 'confirmed',
    platform: 'opentable',
    externalBookingId: 'OT-' + Math.random().toString(36).substr(2, 9).toUpperCase(),
    specialRequests: 'Window table if possible',
  });

  console.log('✓ Created test bookings and reviews');
}

async function main() {
  try {
    console.log('Starting database seed...\n');

    await seedRestaurants();
    const user = await seedTestUser();
    await seedTestBookingsAndReviews(user.id);

    console.log('\n✓ Database seeded successfully!');
    console.log('\nTest account:');
    console.log('  Email: test@example.com');
    console.log('  Password: password123');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

main();
